// This file is generated by scripts/generate-theme-color-data.mjs.
// Edit docs/theme-colors/yemind_theme_colors.json for the 19 source themes.

export type ThemeColorCategory = '基础' | '缤纷' | '经典';
export type ThemeColorAppearanceMode = 'light' | 'dark' | 'fixed';

export interface ThemeColorBranch {
  centerToLevel1Line: string;
  level1Text: string;
  level1Background: string;
  level1ToLevel2Line: string;
  level2Text: string;
  level2Background: string;
  level2ToNormalLine: string;
  normalText: string;
  normalBackground: string;
}

export interface ThemeColorAppearance {
  id: string;
  presetId: string;
  name: string;
  category: ThemeColorCategory;
  appearance: ThemeColorAppearanceMode;
  background: string;
  centerText: string;
  centerBackground: string;
  cycleLength: 1 | 3 | 4 | 6;
  branches: readonly ThemeColorBranch[];
}

export const YEMIND_THEME_SOURCE_NAMES = [
  "晨曦",
  "彩虹",
  "活力",
  "舞动",
  "代码",
  "和风",
  "岛屿",
  "玫瑰",
  "薄荷",
  "绿茶",
  "永恒",
  "奶油",
  "花海",
  "珊瑚",
  "绚丽",
  "香槟",
  "香水",
  "禅心",
  "律动"
] as const;

export const YEMIND_THEME_COLOR_APPEARANCES = [
  {
    "id": "yemind-default-light",
    "presetId": "yemind-default",
    "name": "YeMind 默认",
    "category": "基础",
    "appearance": "light",
    "background": "#F8FAFC",
    "centerText": "#0F172A",
    "centerBackground": "#FFFFFF",
    "cycleLength": 1,
    "branches": [
      {
        "centerToLevel1Line": "#94A3B8",
        "level1Text": "#0F172A",
        "level1Background": "#FFFFFF",
        "level1ToLevel2Line": "#94A3B8",
        "level2Text": "#0F172A",
        "level2Background": "#FFFFFF",
        "level2ToNormalLine": "#94A3B8",
        "normalText": "#0F172A",
        "normalBackground": "#FFFFFF"
      },
      {
        "centerToLevel1Line": "#94A3B8",
        "level1Text": "#0F172A",
        "level1Background": "#FFFFFF",
        "level1ToLevel2Line": "#94A3B8",
        "level2Text": "#0F172A",
        "level2Background": "#FFFFFF",
        "level2ToNormalLine": "#94A3B8",
        "normalText": "#0F172A",
        "normalBackground": "#FFFFFF"
      },
      {
        "centerToLevel1Line": "#94A3B8",
        "level1Text": "#0F172A",
        "level1Background": "#FFFFFF",
        "level1ToLevel2Line": "#94A3B8",
        "level2Text": "#0F172A",
        "level2Background": "#FFFFFF",
        "level2ToNormalLine": "#94A3B8",
        "normalText": "#0F172A",
        "normalBackground": "#FFFFFF"
      },
      {
        "centerToLevel1Line": "#94A3B8",
        "level1Text": "#0F172A",
        "level1Background": "#FFFFFF",
        "level1ToLevel2Line": "#94A3B8",
        "level2Text": "#0F172A",
        "level2Background": "#FFFFFF",
        "level2ToNormalLine": "#94A3B8",
        "normalText": "#0F172A",
        "normalBackground": "#FFFFFF"
      },
      {
        "centerToLevel1Line": "#94A3B8",
        "level1Text": "#0F172A",
        "level1Background": "#FFFFFF",
        "level1ToLevel2Line": "#94A3B8",
        "level2Text": "#0F172A",
        "level2Background": "#FFFFFF",
        "level2ToNormalLine": "#94A3B8",
        "normalText": "#0F172A",
        "normalBackground": "#FFFFFF"
      },
      {
        "centerToLevel1Line": "#94A3B8",
        "level1Text": "#0F172A",
        "level1Background": "#FFFFFF",
        "level1ToLevel2Line": "#94A3B8",
        "level2Text": "#0F172A",
        "level2Background": "#FFFFFF",
        "level2ToNormalLine": "#94A3B8",
        "normalText": "#0F172A",
        "normalBackground": "#FFFFFF"
      }
    ]
  },
  {
    "id": "yemind-default-dark",
    "presetId": "yemind-default",
    "name": "YeMind 默认",
    "category": "基础",
    "appearance": "dark",
    "background": "#0B1220",
    "centerText": "#E2E8F0",
    "centerBackground": "#0B1220",
    "cycleLength": 1,
    "branches": [
      {
        "centerToLevel1Line": "#94A3B8",
        "level1Text": "#E2E8F0",
        "level1Background": "#0B1220",
        "level1ToLevel2Line": "#94A3B8",
        "level2Text": "#E2E8F0",
        "level2Background": "#0B1220",
        "level2ToNormalLine": "#94A3B8",
        "normalText": "#E2E8F0",
        "normalBackground": "#0B1220"
      },
      {
        "centerToLevel1Line": "#94A3B8",
        "level1Text": "#E2E8F0",
        "level1Background": "#0B1220",
        "level1ToLevel2Line": "#94A3B8",
        "level2Text": "#E2E8F0",
        "level2Background": "#0B1220",
        "level2ToNormalLine": "#94A3B8",
        "normalText": "#E2E8F0",
        "normalBackground": "#0B1220"
      },
      {
        "centerToLevel1Line": "#94A3B8",
        "level1Text": "#E2E8F0",
        "level1Background": "#0B1220",
        "level1ToLevel2Line": "#94A3B8",
        "level2Text": "#E2E8F0",
        "level2Background": "#0B1220",
        "level2ToNormalLine": "#94A3B8",
        "normalText": "#E2E8F0",
        "normalBackground": "#0B1220"
      },
      {
        "centerToLevel1Line": "#94A3B8",
        "level1Text": "#E2E8F0",
        "level1Background": "#0B1220",
        "level1ToLevel2Line": "#94A3B8",
        "level2Text": "#E2E8F0",
        "level2Background": "#0B1220",
        "level2ToNormalLine": "#94A3B8",
        "normalText": "#E2E8F0",
        "normalBackground": "#0B1220"
      },
      {
        "centerToLevel1Line": "#94A3B8",
        "level1Text": "#E2E8F0",
        "level1Background": "#0B1220",
        "level1ToLevel2Line": "#94A3B8",
        "level2Text": "#E2E8F0",
        "level2Background": "#0B1220",
        "level2ToNormalLine": "#94A3B8",
        "normalText": "#E2E8F0",
        "normalBackground": "#0B1220"
      },
      {
        "centerToLevel1Line": "#94A3B8",
        "level1Text": "#E2E8F0",
        "level1Background": "#0B1220",
        "level1ToLevel2Line": "#94A3B8",
        "level2Text": "#E2E8F0",
        "level2Background": "#0B1220",
        "level2ToNormalLine": "#94A3B8",
        "normalText": "#E2E8F0",
        "normalBackground": "#0B1220"
      }
    ]
  },
  {
    "id": "ink-branch-light",
    "presetId": "ink-branch",
    "name": "Ink Branch",
    "category": "基础",
    "appearance": "light",
    "background": "#FFFFFF",
    "centerText": "#3749B5",
    "centerBackground": "transparent",
    "cycleLength": 1,
    "branches": [
      {
        "centerToLevel1Line": "#151515",
        "level1Text": "#111111",
        "level1Background": "transparent",
        "level1ToLevel2Line": "#151515",
        "level2Text": "#111111",
        "level2Background": "transparent",
        "level2ToNormalLine": "#151515",
        "normalText": "#111111",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#151515",
        "level1Text": "#111111",
        "level1Background": "transparent",
        "level1ToLevel2Line": "#151515",
        "level2Text": "#111111",
        "level2Background": "transparent",
        "level2ToNormalLine": "#151515",
        "normalText": "#111111",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#151515",
        "level1Text": "#111111",
        "level1Background": "transparent",
        "level1ToLevel2Line": "#151515",
        "level2Text": "#111111",
        "level2Background": "transparent",
        "level2ToNormalLine": "#151515",
        "normalText": "#111111",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#151515",
        "level1Text": "#111111",
        "level1Background": "transparent",
        "level1ToLevel2Line": "#151515",
        "level2Text": "#111111",
        "level2Background": "transparent",
        "level2ToNormalLine": "#151515",
        "normalText": "#111111",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#151515",
        "level1Text": "#111111",
        "level1Background": "transparent",
        "level1ToLevel2Line": "#151515",
        "level2Text": "#111111",
        "level2Background": "transparent",
        "level2ToNormalLine": "#151515",
        "normalText": "#111111",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#151515",
        "level1Text": "#111111",
        "level1Background": "transparent",
        "level1ToLevel2Line": "#151515",
        "level2Text": "#111111",
        "level2Background": "transparent",
        "level2ToNormalLine": "#151515",
        "normalText": "#111111",
        "normalBackground": "transparent"
      }
    ]
  },
  {
    "id": "ink-branch-dark",
    "presetId": "ink-branch",
    "name": "Ink Branch",
    "category": "基础",
    "appearance": "dark",
    "background": "#0A0A0A",
    "centerText": "#93A4FF",
    "centerBackground": "transparent",
    "cycleLength": 1,
    "branches": [
      {
        "centerToLevel1Line": "#F5F5F5",
        "level1Text": "#F5F5F5",
        "level1Background": "transparent",
        "level1ToLevel2Line": "#F5F5F5",
        "level2Text": "#F5F5F5",
        "level2Background": "transparent",
        "level2ToNormalLine": "#F5F5F5",
        "normalText": "#F5F5F5",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#F5F5F5",
        "level1Text": "#F5F5F5",
        "level1Background": "transparent",
        "level1ToLevel2Line": "#F5F5F5",
        "level2Text": "#F5F5F5",
        "level2Background": "transparent",
        "level2ToNormalLine": "#F5F5F5",
        "normalText": "#F5F5F5",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#F5F5F5",
        "level1Text": "#F5F5F5",
        "level1Background": "transparent",
        "level1ToLevel2Line": "#F5F5F5",
        "level2Text": "#F5F5F5",
        "level2Background": "transparent",
        "level2ToNormalLine": "#F5F5F5",
        "normalText": "#F5F5F5",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#F5F5F5",
        "level1Text": "#F5F5F5",
        "level1Background": "transparent",
        "level1ToLevel2Line": "#F5F5F5",
        "level2Text": "#F5F5F5",
        "level2Background": "transparent",
        "level2ToNormalLine": "#F5F5F5",
        "normalText": "#F5F5F5",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#F5F5F5",
        "level1Text": "#F5F5F5",
        "level1Background": "transparent",
        "level1ToLevel2Line": "#F5F5F5",
        "level2Text": "#F5F5F5",
        "level2Background": "transparent",
        "level2ToNormalLine": "#F5F5F5",
        "normalText": "#F5F5F5",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#F5F5F5",
        "level1Text": "#F5F5F5",
        "level1Background": "transparent",
        "level1ToLevel2Line": "#F5F5F5",
        "level2Text": "#F5F5F5",
        "level2Background": "transparent",
        "level2ToNormalLine": "#F5F5F5",
        "normalText": "#F5F5F5",
        "normalBackground": "transparent"
      }
    ]
  },
  {
    "id": "material-3-basic-light",
    "presetId": "material-3-basic",
    "name": "Material 3 Basic",
    "category": "基础",
    "appearance": "light",
    "background": "#FEF7FF",
    "centerText": "#21005D",
    "centerBackground": "#EADDFF",
    "cycleLength": 1,
    "branches": [
      {
        "centerToLevel1Line": "#79747E",
        "level1Text": "#1D192B",
        "level1Background": "#E8DEF8",
        "level1ToLevel2Line": "#79747E",
        "level2Text": "#1C1B1F",
        "level2Background": "#F3EDF7",
        "level2ToNormalLine": "#79747E",
        "normalText": "#1C1B1F",
        "normalBackground": "#F3EDF7"
      },
      {
        "centerToLevel1Line": "#79747E",
        "level1Text": "#1D192B",
        "level1Background": "#E8DEF8",
        "level1ToLevel2Line": "#79747E",
        "level2Text": "#1C1B1F",
        "level2Background": "#F3EDF7",
        "level2ToNormalLine": "#79747E",
        "normalText": "#1C1B1F",
        "normalBackground": "#F3EDF7"
      },
      {
        "centerToLevel1Line": "#79747E",
        "level1Text": "#1D192B",
        "level1Background": "#E8DEF8",
        "level1ToLevel2Line": "#79747E",
        "level2Text": "#1C1B1F",
        "level2Background": "#F3EDF7",
        "level2ToNormalLine": "#79747E",
        "normalText": "#1C1B1F",
        "normalBackground": "#F3EDF7"
      },
      {
        "centerToLevel1Line": "#79747E",
        "level1Text": "#1D192B",
        "level1Background": "#E8DEF8",
        "level1ToLevel2Line": "#79747E",
        "level2Text": "#1C1B1F",
        "level2Background": "#F3EDF7",
        "level2ToNormalLine": "#79747E",
        "normalText": "#1C1B1F",
        "normalBackground": "#F3EDF7"
      },
      {
        "centerToLevel1Line": "#79747E",
        "level1Text": "#1D192B",
        "level1Background": "#E8DEF8",
        "level1ToLevel2Line": "#79747E",
        "level2Text": "#1C1B1F",
        "level2Background": "#F3EDF7",
        "level2ToNormalLine": "#79747E",
        "normalText": "#1C1B1F",
        "normalBackground": "#F3EDF7"
      },
      {
        "centerToLevel1Line": "#79747E",
        "level1Text": "#1D192B",
        "level1Background": "#E8DEF8",
        "level1ToLevel2Line": "#79747E",
        "level2Text": "#1C1B1F",
        "level2Background": "#F3EDF7",
        "level2ToNormalLine": "#79747E",
        "normalText": "#1C1B1F",
        "normalBackground": "#F3EDF7"
      }
    ]
  },
  {
    "id": "material-3-basic-dark",
    "presetId": "material-3-basic",
    "name": "Material 3 Basic",
    "category": "基础",
    "appearance": "dark",
    "background": "#141218",
    "centerText": "#FEF7FF",
    "centerBackground": "#4F378B",
    "cycleLength": 1,
    "branches": [
      {
        "centerToLevel1Line": "#938F99",
        "level1Text": "#E6E1E5",
        "level1Background": "#332D41",
        "level1ToLevel2Line": "#938F99",
        "level2Text": "#E6E1E5",
        "level2Background": "#211F26",
        "level2ToNormalLine": "#938F99",
        "normalText": "#E6E1E5",
        "normalBackground": "#211F26"
      },
      {
        "centerToLevel1Line": "#938F99",
        "level1Text": "#E6E1E5",
        "level1Background": "#332D41",
        "level1ToLevel2Line": "#938F99",
        "level2Text": "#E6E1E5",
        "level2Background": "#211F26",
        "level2ToNormalLine": "#938F99",
        "normalText": "#E6E1E5",
        "normalBackground": "#211F26"
      },
      {
        "centerToLevel1Line": "#938F99",
        "level1Text": "#E6E1E5",
        "level1Background": "#332D41",
        "level1ToLevel2Line": "#938F99",
        "level2Text": "#E6E1E5",
        "level2Background": "#211F26",
        "level2ToNormalLine": "#938F99",
        "normalText": "#E6E1E5",
        "normalBackground": "#211F26"
      },
      {
        "centerToLevel1Line": "#938F99",
        "level1Text": "#E6E1E5",
        "level1Background": "#332D41",
        "level1ToLevel2Line": "#938F99",
        "level2Text": "#E6E1E5",
        "level2Background": "#211F26",
        "level2ToNormalLine": "#938F99",
        "normalText": "#E6E1E5",
        "normalBackground": "#211F26"
      },
      {
        "centerToLevel1Line": "#938F99",
        "level1Text": "#E6E1E5",
        "level1Background": "#332D41",
        "level1ToLevel2Line": "#938F99",
        "level2Text": "#E6E1E5",
        "level2Background": "#211F26",
        "level2ToNormalLine": "#938F99",
        "normalText": "#E6E1E5",
        "normalBackground": "#211F26"
      },
      {
        "centerToLevel1Line": "#938F99",
        "level1Text": "#E6E1E5",
        "level1Background": "#332D41",
        "level1ToLevel2Line": "#938F99",
        "level2Text": "#E6E1E5",
        "level2Background": "#211F26",
        "level2ToNormalLine": "#938F99",
        "normalText": "#E6E1E5",
        "normalBackground": "#211F26"
      }
    ]
  },
  {
    "id": "scheme-dawn",
    "presetId": "scheme-dawn",
    "name": "晨曦",
    "category": "缤纷",
    "appearance": "fixed",
    "background": "#FFFFFF",
    "centerText": "#000000",
    "centerBackground": "transparent",
    "cycleLength": 6,
    "branches": [
      {
        "centerToLevel1Line": "#FF6B6B",
        "level1Text": "#000000",
        "level1Background": "#FF6B6B",
        "level1ToLevel2Line": "#FF6B6B",
        "level2Text": "#660000",
        "level2Background": "#FEE0E0",
        "level2ToNormalLine": "#FF6B6B",
        "normalText": "#660000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#FF9F69",
        "level1Text": "#000000",
        "level1Background": "#FF9F69",
        "level1ToLevel2Line": "#FF9F69",
        "level2Text": "#662400",
        "level2Background": "#FEEBE0",
        "level2ToNormalLine": "#FF9F69",
        "normalText": "#662400",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#97D3B6",
        "level1Text": "#000000",
        "level1Background": "#97D3B6",
        "level1ToLevel2Line": "#97D3B6",
        "level2Text": "#1E4733",
        "level2Background": "#E9F5EF",
        "level2ToNormalLine": "#97D3B6",
        "normalText": "#1E4733",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#88E2D7",
        "level1Text": "#000000",
        "level1Background": "#88E2D7",
        "level1ToLevel2Line": "#88E2D7",
        "level2Text": "#13524A",
        "level2Background": "#E7F9F7",
        "level2ToNormalLine": "#88E2D7",
        "normalText": "#13524A",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#6FD0F9",
        "level1Text": "#000000",
        "level1Background": "#6FD0F9",
        "level1ToLevel2Line": "#6FD0F9",
        "level2Text": "#044661",
        "level2Background": "#E2F6FE",
        "level2ToNormalLine": "#6FD0F9",
        "normalText": "#044661",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#E18BEE",
        "level1Text": "#000000",
        "level1Background": "#E18BEE",
        "level1ToLevel2Line": "#E18BEE",
        "level2Text": "#4E0D58",
        "level2Background": "#F9E8FC",
        "level2ToNormalLine": "#E18BEE",
        "normalText": "#4E0D58",
        "normalBackground": "transparent"
      }
    ]
  },
  {
    "id": "scheme-rainbow",
    "presetId": "scheme-rainbow",
    "name": "彩虹",
    "category": "缤纷",
    "appearance": "fixed",
    "background": "#FFFFFF",
    "centerText": "#000229",
    "centerBackground": "transparent",
    "cycleLength": 6,
    "branches": [
      {
        "centerToLevel1Line": "#F9423A",
        "level1Text": "#FFFFFF",
        "level1Background": "#F9423A",
        "level1ToLevel2Line": "#F9423A",
        "level2Text": "#620703",
        "level2Background": "#FDD8D7",
        "level2ToNormalLine": "#F9423A",
        "normalText": "#620703",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#F6A04D",
        "level1Text": "#000000",
        "level1Background": "#F6A04D",
        "level1ToLevel2Line": "#F6A04D",
        "level2Text": "#613204",
        "level2Background": "#FCEBDA",
        "level2ToNormalLine": "#F6A04D",
        "normalText": "#613204",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#F3D321",
        "level1Text": "#000000",
        "level1Background": "#F3D321",
        "level1ToLevel2Line": "#F3D321",
        "level2Text": "#605205",
        "level2Background": "#FCF5D2",
        "level2ToNormalLine": "#F3D321",
        "normalText": "#605205",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#00BC7B",
        "level1Text": "#000000",
        "level1Background": "#00BC7B",
        "level1ToLevel2Line": "#00BC7B",
        "level2Text": "#006642",
        "level2Background": "#CCF2E5",
        "level2ToNormalLine": "#00BC7B",
        "normalText": "#006642",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#486AFF",
        "level1Text": "#FFFFFF",
        "level1Background": "#486AFF",
        "level1ToLevel2Line": "#486AFF",
        "level2Text": "#001266",
        "level2Background": "#DAE1FF",
        "level2ToNormalLine": "#486AFF",
        "normalText": "#001266",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#4D49BE",
        "level1Text": "#FFFFFF",
        "level1Background": "#4D49BE",
        "level1ToLevel2Line": "#4D49BE",
        "level2Text": "#1C1A4B",
        "level2Background": "#DBDBF2",
        "level2ToNormalLine": "#4D49BE",
        "normalText": "#1C1A4B",
        "normalBackground": "transparent"
      }
    ]
  },
  {
    "id": "scheme-vitality",
    "presetId": "scheme-vitality",
    "name": "活力",
    "category": "缤纷",
    "appearance": "fixed",
    "background": "#FFFFFF",
    "centerText": "#000000",
    "centerBackground": "transparent",
    "cycleLength": 3,
    "branches": [
      {
        "centerToLevel1Line": "#F22816",
        "level1Text": "#FFFFFF",
        "level1Background": "#F22816",
        "level1ToLevel2Line": "#F22816",
        "level2Text": "#600C05",
        "level2Background": "#FCD4D0",
        "level2ToNormalLine": "#F22816",
        "normalText": "#600C05",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#F2B807",
        "level1Text": "#000000",
        "level1Background": "#F2B807",
        "level1ToLevel2Line": "#F2B807",
        "level2Text": "#634B02",
        "level2Background": "#FCF1CD",
        "level2ToNormalLine": "#F2B807",
        "normalText": "#634B02",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#233ED9",
        "level1Text": "#FFFFFF",
        "level1Background": "#233ED9",
        "level1ToLevel2Line": "#233ED9",
        "level2Text": "#0E1957",
        "level2Background": "#D3D8F7",
        "level2ToNormalLine": "#233ED9",
        "normalText": "#0E1957",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#F22816",
        "level1Text": "#FFFFFF",
        "level1Background": "#F22816",
        "level1ToLevel2Line": "#F22816",
        "level2Text": "#600C05",
        "level2Background": "#FCD4D0",
        "level2ToNormalLine": "#F22816",
        "normalText": "#600C05",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#F2B807",
        "level1Text": "#000000",
        "level1Background": "#F2B807",
        "level1ToLevel2Line": "#F2B807",
        "level2Text": "#634B02",
        "level2Background": "#FCF1CD",
        "level2ToNormalLine": "#F2B807",
        "normalText": "#634B02",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#233ED9",
        "level1Text": "#FFFFFF",
        "level1Background": "#233ED9",
        "level1ToLevel2Line": "#233ED9",
        "level2Text": "#0E1957",
        "level2Background": "#D3D8F7",
        "level2ToNormalLine": "#233ED9",
        "normalText": "#0E1957",
        "normalBackground": "transparent"
      }
    ]
  },
  {
    "id": "scheme-dance",
    "presetId": "scheme-dance",
    "name": "舞动",
    "category": "缤纷",
    "appearance": "fixed",
    "background": "#FFFFFF",
    "centerText": "#363026",
    "centerBackground": "transparent",
    "cycleLength": 3,
    "branches": [
      {
        "centerToLevel1Line": "#4E60EF",
        "level1Text": "#FFFFFF",
        "level1Background": "#4E60EF",
        "level1ToLevel2Line": "#4E60EF",
        "level2Text": "#08115D",
        "level2Background": "#DCDFFC",
        "level2ToNormalLine": "#4E60EF",
        "normalText": "#08115D",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#EB4758",
        "level1Text": "#FFFFFF",
        "level1Background": "#EB4758",
        "level1ToLevel2Line": "#EB4758",
        "level2Text": "#5C0A12",
        "level2Background": "#FBDADE",
        "level2ToNormalLine": "#EB4758",
        "normalText": "#5C0A12",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#AA0E1D",
        "level1Text": "#FFFFFF",
        "level1Background": "#AA0E1D",
        "level1ToLevel2Line": "#AA0E1D",
        "level2Text": "#5E0710",
        "level2Background": "#EECFD2",
        "level2ToNormalLine": "#AA0E1D",
        "normalText": "#5E0710",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#4E60EF",
        "level1Text": "#FFFFFF",
        "level1Background": "#4E60EF",
        "level1ToLevel2Line": "#4E60EF",
        "level2Text": "#08115D",
        "level2Background": "#DCDFFC",
        "level2ToNormalLine": "#4E60EF",
        "normalText": "#08115D",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#EB4758",
        "level1Text": "#FFFFFF",
        "level1Background": "#EB4758",
        "level1ToLevel2Line": "#EB4758",
        "level2Text": "#5C0A12",
        "level2Background": "#FBDADE",
        "level2ToNormalLine": "#EB4758",
        "normalText": "#5C0A12",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#AA0E1D",
        "level1Text": "#FFFFFF",
        "level1Background": "#AA0E1D",
        "level1ToLevel2Line": "#AA0E1D",
        "level2Text": "#5E0710",
        "level2Background": "#EECFD2",
        "level2ToNormalLine": "#AA0E1D",
        "normalText": "#5E0710",
        "normalBackground": "transparent"
      }
    ]
  },
  {
    "id": "scheme-code",
    "presetId": "scheme-code",
    "name": "代码",
    "category": "缤纷",
    "appearance": "fixed",
    "background": "#2C2D30",
    "centerText": "#FFFFFF",
    "centerBackground": "transparent",
    "cycleLength": 4,
    "branches": [
      {
        "centerToLevel1Line": "#FFF0B8",
        "level1Text": "#000000",
        "level1Background": "#FFF0B8",
        "level1ToLevel2Line": "#FFF0B8",
        "level2Text": "#FFFFFF",
        "level2Background": "#56544B",
        "level2ToNormalLine": "#FFF0B8",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#CBFFB8",
        "level1Text": "#000000",
        "level1Background": "#CBFFB8",
        "level1ToLevel2Line": "#CBFFB8",
        "level2Text": "#FFFFFF",
        "level2Background": "#4C574B",
        "level2ToNormalLine": "#CBFFB8",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#DB8FFF",
        "level1Text": "#000000",
        "level1Background": "#DB8FFF",
        "level1ToLevel2Line": "#DB8FFF",
        "level2Text": "#FFFFFF",
        "level2Background": "#4F4159",
        "level2ToNormalLine": "#DB8FFF",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#8ABEFF",
        "level1Text": "#000000",
        "level1Background": "#8ABEFF",
        "level1ToLevel2Line": "#8ABEFF",
        "level2Text": "#FFFFFF",
        "level2Background": "#3F4A59",
        "level2ToNormalLine": "#8ABEFF",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#FFF0B8",
        "level1Text": "#000000",
        "level1Background": "#FFF0B8",
        "level1ToLevel2Line": "#FFF0B8",
        "level2Text": "#FFFFFF",
        "level2Background": "#56544B",
        "level2ToNormalLine": "#FFF0B8",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#CBFFB8",
        "level1Text": "#000000",
        "level1Background": "#CBFFB8",
        "level1ToLevel2Line": "#CBFFB8",
        "level2Text": "#FFFFFF",
        "level2Background": "#4C574B",
        "level2ToNormalLine": "#CBFFB8",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      }
    ]
  },
  {
    "id": "scheme-harmony",
    "presetId": "scheme-harmony",
    "name": "和风",
    "category": "缤纷",
    "appearance": "fixed",
    "background": "#FFFFFF",
    "centerText": "#191959",
    "centerBackground": "transparent",
    "cycleLength": 4,
    "branches": [
      {
        "centerToLevel1Line": "#FFABAA",
        "level1Text": "#000000",
        "level1Background": "#FFABAA",
        "level1ToLevel2Line": "#FFABAA",
        "level2Text": "#660100",
        "level2Background": "#FFEEEE",
        "level2ToNormalLine": "#FFABAA",
        "normalText": "#660100",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#FF7B31",
        "level1Text": "#000000",
        "level1Background": "#FF7B31",
        "level1ToLevel2Line": "#FF7B31",
        "level2Text": "#662400",
        "level2Background": "#FFE5D6",
        "level2ToNormalLine": "#FF7B31",
        "normalText": "#662400",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#8CB5FF",
        "level1Text": "#000000",
        "level1Background": "#8CB5FF",
        "level1ToLevel2Line": "#8CB5FF",
        "level2Text": "#002466",
        "level2Background": "#E7EFFE",
        "level2ToNormalLine": "#8CB5FF",
        "normalText": "#002466",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#4A51D9",
        "level1Text": "#FFFFFF",
        "level1Background": "#4A51D9",
        "level1ToLevel2Line": "#4A51D9",
        "level2Text": "#111454",
        "level2Background": "#DBDCF7",
        "level2ToNormalLine": "#4A51D9",
        "normalText": "#111454",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#FFABAA",
        "level1Text": "#000000",
        "level1Background": "#FFABAA",
        "level1ToLevel2Line": "#FFABAA",
        "level2Text": "#660100",
        "level2Background": "#FFEEEE",
        "level2ToNormalLine": "#FFABAA",
        "normalText": "#660100",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#FF7B31",
        "level1Text": "#000000",
        "level1Background": "#FF7B31",
        "level1ToLevel2Line": "#FF7B31",
        "level2Text": "#662400",
        "level2Background": "#FFE5D6",
        "level2ToNormalLine": "#FF7B31",
        "normalText": "#662400",
        "normalBackground": "transparent"
      }
    ]
  },
  {
    "id": "scheme-island",
    "presetId": "scheme-island",
    "name": "岛屿",
    "category": "缤纷",
    "appearance": "fixed",
    "background": "#FFE8D6",
    "centerText": "#6B705C",
    "centerBackground": "transparent",
    "cycleLength": 4,
    "branches": [
      {
        "centerToLevel1Line": "#DDBEA9",
        "level1Text": "#000000",
        "level1Background": "#DDBEA9",
        "level1ToLevel2Line": "#DDBEA9",
        "level2Text": "#492E1C",
        "level2Background": "#F8E0CD",
        "level2ToNormalLine": "#DDBEA9",
        "normalText": "#492E1C",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#CB997E",
        "level1Text": "#000000",
        "level1Background": "#CB997E",
        "level1ToLevel2Line": "#CB997E",
        "level2Text": "#482C1D",
        "level2Background": "#F5D9C4",
        "level2ToNormalLine": "#CB997E",
        "normalText": "#482C1D",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#B7B7A4",
        "level1Text": "#000000",
        "level1Background": "#B7B7A4",
        "level1ToLevel2Line": "#B7B7A4",
        "level2Text": "#38392D",
        "level2Background": "#F0DECB",
        "level2ToNormalLine": "#B7B7A4",
        "normalText": "#38392D",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#A5A58D",
        "level1Text": "#000000",
        "level1Background": "#A5A58D",
        "level1ToLevel2Line": "#A5A58D",
        "level2Text": "#38392D",
        "level2Background": "#EDDBC7",
        "level2ToNormalLine": "#A5A58D",
        "normalText": "#38392D",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#DDBEA9",
        "level1Text": "#000000",
        "level1Background": "#DDBEA9",
        "level1ToLevel2Line": "#DDBEA9",
        "level2Text": "#492E1C",
        "level2Background": "#F8E0CD",
        "level2ToNormalLine": "#DDBEA9",
        "normalText": "#492E1C",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#CB997E",
        "level1Text": "#000000",
        "level1Background": "#CB997E",
        "level1ToLevel2Line": "#CB997E",
        "level2Text": "#482C1D",
        "level2Background": "#F5D9C4",
        "level2ToNormalLine": "#CB997E",
        "normalText": "#482C1D",
        "normalBackground": "transparent"
      }
    ]
  },
  {
    "id": "scheme-rose",
    "presetId": "scheme-rose",
    "name": "玫瑰",
    "category": "缤纷",
    "appearance": "fixed",
    "background": "#FFF0F3",
    "centerText": "#A4133C",
    "centerBackground": "transparent",
    "cycleLength": 3,
    "branches": [
      {
        "centerToLevel1Line": "#FFB3C1",
        "level1Text": "#000000",
        "level1Background": "#FFB3C1",
        "level1ToLevel2Line": "#FFB3C1",
        "level2Text": "#660012",
        "level2Background": "#FFE4E9",
        "level2ToNormalLine": "#FFB3C1",
        "normalText": "#660012",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#FF758F",
        "level1Text": "#000000",
        "level1Background": "#FF758F",
        "level1ToLevel2Line": "#FF758F",
        "level2Text": "#660013",
        "level2Background": "#FFD7DF",
        "level2ToNormalLine": "#FF758F",
        "normalText": "#660013",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#C9184A",
        "level1Text": "#FFFFFF",
        "level1Background": "#C9184A",
        "level1ToLevel2Line": "#C9184A",
        "level2Text": "#5B0A21",
        "level2Background": "#F4C5D1",
        "level2ToNormalLine": "#C9184A",
        "normalText": "#5B0A21",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#FFB3C1",
        "level1Text": "#000000",
        "level1Background": "#FFB3C1",
        "level1ToLevel2Line": "#FFB3C1",
        "level2Text": "#660012",
        "level2Background": "#FFE4E9",
        "level2ToNormalLine": "#FFB3C1",
        "normalText": "#660012",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#FF758F",
        "level1Text": "#000000",
        "level1Background": "#FF758F",
        "level1ToLevel2Line": "#FF758F",
        "level2Text": "#660013",
        "level2Background": "#FFD7DF",
        "level2ToNormalLine": "#FF758F",
        "normalText": "#660013",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#C9184A",
        "level1Text": "#FFFFFF",
        "level1Background": "#C9184A",
        "level1ToLevel2Line": "#C9184A",
        "level2Text": "#5B0A21",
        "level2Background": "#F4C5D1",
        "level2ToNormalLine": "#C9184A",
        "normalText": "#5B0A21",
        "normalBackground": "transparent"
      }
    ]
  },
  {
    "id": "scheme-mint",
    "presetId": "scheme-mint",
    "name": "薄荷",
    "category": "缤纷",
    "appearance": "fixed",
    "background": "#FFFFFF",
    "centerText": "#046562",
    "centerBackground": "transparent",
    "cycleLength": 3,
    "branches": [
      {
        "centerToLevel1Line": "#9CEAEF",
        "level1Text": "#000000",
        "level1Background": "#9CEAEF",
        "level1ToLevel2Line": "#9CEAEF",
        "level2Text": "#0E5357",
        "level2Background": "#EBFBFC",
        "level2ToNormalLine": "#9CEAEF",
        "normalText": "#0E5357",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#68D8D6",
        "level1Text": "#000000",
        "level1Background": "#68D8D6",
        "level1ToLevel2Line": "#68D8D6",
        "level2Text": "#14514F",
        "level2Background": "#E1F7F7",
        "level2ToNormalLine": "#68D8D6",
        "normalText": "#14514F",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#06AFA9",
        "level1Text": "#000000",
        "level1Background": "#06AFA9",
        "level1ToLevel2Line": "#06AFA9",
        "level2Text": "#03625F",
        "level2Background": "#CDEFEE",
        "level2ToNormalLine": "#06AFA9",
        "normalText": "#03625F",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#9CEAEF",
        "level1Text": "#000000",
        "level1Background": "#9CEAEF",
        "level1ToLevel2Line": "#9CEAEF",
        "level2Text": "#0E5357",
        "level2Background": "#EBFBFC",
        "level2ToNormalLine": "#9CEAEF",
        "normalText": "#0E5357",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#68D8D6",
        "level1Text": "#000000",
        "level1Background": "#68D8D6",
        "level1ToLevel2Line": "#68D8D6",
        "level2Text": "#14514F",
        "level2Background": "#E1F7F7",
        "level2ToNormalLine": "#68D8D6",
        "normalText": "#14514F",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#06AFA9",
        "level1Text": "#000000",
        "level1Background": "#06AFA9",
        "level1ToLevel2Line": "#06AFA9",
        "level2Text": "#03625F",
        "level2Background": "#CDEFEE",
        "level2ToNormalLine": "#06AFA9",
        "normalText": "#03625F",
        "normalBackground": "transparent"
      }
    ]
  },
  {
    "id": "scheme-green-tea",
    "presetId": "scheme-green-tea",
    "name": "绿茶",
    "category": "缤纷",
    "appearance": "fixed",
    "background": "#1F2B1D",
    "centerText": "#D6D9C3",
    "centerBackground": "transparent",
    "cycleLength": 4,
    "branches": [
      {
        "centerToLevel1Line": "#B6AD90",
        "level1Text": "#000000",
        "level1Background": "#B6AD90",
        "level1ToLevel2Line": "#B6AD90",
        "level2Text": "#FFFFFF",
        "level2Background": "#3D4534",
        "level2ToNormalLine": "#B6AD90",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#579360",
        "level1Text": "#FFFFFF",
        "level1Background": "#579360",
        "level1ToLevel2Line": "#579360",
        "level2Text": "#FFFFFF",
        "level2Background": "#2A3F2A",
        "level2ToNormalLine": "#579360",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#656D4A",
        "level1Text": "#FFFFFF",
        "level1Background": "#656D4A",
        "level1ToLevel2Line": "#656D4A",
        "level2Text": "#FFFFFF",
        "level2Background": "#2D3826",
        "level2ToNormalLine": "#656D4A",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#265834",
        "level1Text": "#FFFFFF",
        "level1Background": "#265834",
        "level1ToLevel2Line": "#265834",
        "level2Text": "#FFFFFF",
        "level2Background": "#213421",
        "level2ToNormalLine": "#265834",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#B6AD90",
        "level1Text": "#000000",
        "level1Background": "#B6AD90",
        "level1ToLevel2Line": "#B6AD90",
        "level2Text": "#FFFFFF",
        "level2Background": "#3D4534",
        "level2ToNormalLine": "#B6AD90",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#579360",
        "level1Text": "#FFFFFF",
        "level1Background": "#579360",
        "level1ToLevel2Line": "#579360",
        "level2Text": "#FFFFFF",
        "level2Background": "#2A3F2A",
        "level2ToNormalLine": "#579360",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      }
    ]
  },
  {
    "id": "scheme-eternity",
    "presetId": "scheme-eternity",
    "name": "永恒",
    "category": "经典",
    "appearance": "fixed",
    "background": "#FFFFFF",
    "centerText": "#3949AB",
    "centerBackground": "transparent",
    "cycleLength": 1,
    "branches": [
      {
        "centerToLevel1Line": "#141414",
        "level1Text": "#000000",
        "level1Background": "#EEEEEE",
        "level1ToLevel2Line": "#141414",
        "level2Text": "#000000",
        "level2Background": "#EEEEEE",
        "level2ToNormalLine": "#141414",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#141414",
        "level1Text": "#000000",
        "level1Background": "#EEEEEE",
        "level1ToLevel2Line": "#141414",
        "level2Text": "#000000",
        "level2Background": "#EEEEEE",
        "level2ToNormalLine": "#141414",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#141414",
        "level1Text": "#000000",
        "level1Background": "#EEEEEE",
        "level1ToLevel2Line": "#141414",
        "level2Text": "#000000",
        "level2Background": "#EEEEEE",
        "level2ToNormalLine": "#141414",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#141414",
        "level1Text": "#000000",
        "level1Background": "#EEEEEE",
        "level1ToLevel2Line": "#141414",
        "level2Text": "#000000",
        "level2Background": "#EEEEEE",
        "level2ToNormalLine": "#141414",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#141414",
        "level1Text": "#000000",
        "level1Background": "#EEEEEE",
        "level1ToLevel2Line": "#141414",
        "level2Text": "#000000",
        "level2Background": "#EEEEEE",
        "level2ToNormalLine": "#141414",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#141414",
        "level1Text": "#000000",
        "level1Background": "#EEEEEE",
        "level1ToLevel2Line": "#141414",
        "level2Text": "#000000",
        "level2Background": "#EEEEEE",
        "level2ToNormalLine": "#141414",
        "normalText": "#000000",
        "normalBackground": "transparent"
      }
    ]
  },
  {
    "id": "scheme-cream",
    "presetId": "scheme-cream",
    "name": "奶油",
    "category": "经典",
    "appearance": "fixed",
    "background": "#FFE0E5",
    "centerText": "#000000",
    "centerBackground": "transparent",
    "cycleLength": 1,
    "branches": [
      {
        "centerToLevel1Line": "#FFFFFF",
        "level1Text": "#000000",
        "level1Background": "#FFFFFF",
        "level1ToLevel2Line": "#FFFFFF",
        "level2Text": "#000000",
        "level2Background": "#FFFFFF",
        "level2ToNormalLine": "#FFFFFF",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#FFFFFF",
        "level1Text": "#000000",
        "level1Background": "#FFFFFF",
        "level1ToLevel2Line": "#FFFFFF",
        "level2Text": "#000000",
        "level2Background": "#FFFFFF",
        "level2ToNormalLine": "#FFFFFF",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#FFFFFF",
        "level1Text": "#000000",
        "level1Background": "#FFFFFF",
        "level1ToLevel2Line": "#FFFFFF",
        "level2Text": "#000000",
        "level2Background": "#FFFFFF",
        "level2ToNormalLine": "#FFFFFF",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#FFFFFF",
        "level1Text": "#000000",
        "level1Background": "#FFFFFF",
        "level1ToLevel2Line": "#FFFFFF",
        "level2Text": "#000000",
        "level2Background": "#FFFFFF",
        "level2ToNormalLine": "#FFFFFF",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#FFFFFF",
        "level1Text": "#000000",
        "level1Background": "#FFFFFF",
        "level1ToLevel2Line": "#FFFFFF",
        "level2Text": "#000000",
        "level2Background": "#FFFFFF",
        "level2ToNormalLine": "#FFFFFF",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#FFFFFF",
        "level1Text": "#000000",
        "level1Background": "#FFFFFF",
        "level1ToLevel2Line": "#FFFFFF",
        "level2Text": "#000000",
        "level2Background": "#FFFFFF",
        "level2ToNormalLine": "#FFFFFF",
        "normalText": "#000000",
        "normalBackground": "transparent"
      }
    ]
  },
  {
    "id": "scheme-flower-sea",
    "presetId": "scheme-flower-sea",
    "name": "花海",
    "category": "经典",
    "appearance": "fixed",
    "background": "#FFFFFF",
    "centerText": "#A61D39",
    "centerBackground": "transparent",
    "cycleLength": 1,
    "branches": [
      {
        "centerToLevel1Line": "#4A1019",
        "level1Text": "#FFFFFF",
        "level1Background": "#D02F48",
        "level1ToLevel2Line": "#4A1019",
        "level2Text": "#000000",
        "level2Background": "#E5E5E5",
        "level2ToNormalLine": "#4A1019",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#4A1019",
        "level1Text": "#FFFFFF",
        "level1Background": "#D02F48",
        "level1ToLevel2Line": "#4A1019",
        "level2Text": "#000000",
        "level2Background": "#E5E5E5",
        "level2ToNormalLine": "#4A1019",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#4A1019",
        "level1Text": "#FFFFFF",
        "level1Background": "#D02F48",
        "level1ToLevel2Line": "#4A1019",
        "level2Text": "#000000",
        "level2Background": "#E5E5E5",
        "level2ToNormalLine": "#4A1019",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#4A1019",
        "level1Text": "#FFFFFF",
        "level1Background": "#D02F48",
        "level1ToLevel2Line": "#4A1019",
        "level2Text": "#000000",
        "level2Background": "#E5E5E5",
        "level2ToNormalLine": "#4A1019",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#4A1019",
        "level1Text": "#FFFFFF",
        "level1Background": "#D02F48",
        "level1ToLevel2Line": "#4A1019",
        "level2Text": "#000000",
        "level2Background": "#E5E5E5",
        "level2ToNormalLine": "#4A1019",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#4A1019",
        "level1Text": "#FFFFFF",
        "level1Background": "#D02F48",
        "level1ToLevel2Line": "#4A1019",
        "level2Text": "#000000",
        "level2Background": "#E5E5E5",
        "level2ToNormalLine": "#4A1019",
        "normalText": "#000000",
        "normalBackground": "transparent"
      }
    ]
  },
  {
    "id": "scheme-coral",
    "presetId": "scheme-coral",
    "name": "珊瑚",
    "category": "经典",
    "appearance": "fixed",
    "background": "#140407",
    "centerText": "#EF6C70",
    "centerBackground": "transparent",
    "cycleLength": 1,
    "branches": [
      {
        "centerToLevel1Line": "#FDF1F1",
        "level1Text": "#FFFFFF",
        "level1Background": "#D02F48",
        "level1ToLevel2Line": "#FDF1F1",
        "level2Text": "#FFFFFF",
        "level2Background": "#7C1C2B",
        "level2ToNormalLine": "#FDF1F1",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#FDF1F1",
        "level1Text": "#FFFFFF",
        "level1Background": "#D02F48",
        "level1ToLevel2Line": "#FDF1F1",
        "level2Text": "#FFFFFF",
        "level2Background": "#7C1C2B",
        "level2ToNormalLine": "#FDF1F1",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#FDF1F1",
        "level1Text": "#FFFFFF",
        "level1Background": "#D02F48",
        "level1ToLevel2Line": "#FDF1F1",
        "level2Text": "#FFFFFF",
        "level2Background": "#7C1C2B",
        "level2ToNormalLine": "#FDF1F1",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#FDF1F1",
        "level1Text": "#FFFFFF",
        "level1Background": "#D02F48",
        "level1ToLevel2Line": "#FDF1F1",
        "level2Text": "#FFFFFF",
        "level2Background": "#7C1C2B",
        "level2ToNormalLine": "#FDF1F1",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#FDF1F1",
        "level1Text": "#FFFFFF",
        "level1Background": "#D02F48",
        "level1ToLevel2Line": "#FDF1F1",
        "level2Text": "#FFFFFF",
        "level2Background": "#7C1C2B",
        "level2ToNormalLine": "#FDF1F1",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#FDF1F1",
        "level1Text": "#FFFFFF",
        "level1Background": "#D02F48",
        "level1ToLevel2Line": "#FDF1F1",
        "level2Text": "#FFFFFF",
        "level2Background": "#7C1C2B",
        "level2ToNormalLine": "#FDF1F1",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      }
    ]
  },
  {
    "id": "scheme-vivid",
    "presetId": "scheme-vivid",
    "name": "绚丽",
    "category": "经典",
    "appearance": "fixed",
    "background": "#D02F48",
    "centerText": "#000000",
    "centerBackground": "transparent",
    "cycleLength": 1,
    "branches": [
      {
        "centerToLevel1Line": "#FFFFFF",
        "level1Text": "#000000",
        "level1Background": "#FFFFFF",
        "level1ToLevel2Line": "#FFFFFF",
        "level2Text": "#FFFFFF",
        "level2Background": "#7C1C2B",
        "level2ToNormalLine": "#FFFFFF",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#FFFFFF",
        "level1Text": "#000000",
        "level1Background": "#FFFFFF",
        "level1ToLevel2Line": "#FFFFFF",
        "level2Text": "#FFFFFF",
        "level2Background": "#7C1C2B",
        "level2ToNormalLine": "#FFFFFF",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#FFFFFF",
        "level1Text": "#000000",
        "level1Background": "#FFFFFF",
        "level1ToLevel2Line": "#FFFFFF",
        "level2Text": "#FFFFFF",
        "level2Background": "#7C1C2B",
        "level2ToNormalLine": "#FFFFFF",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#FFFFFF",
        "level1Text": "#000000",
        "level1Background": "#FFFFFF",
        "level1ToLevel2Line": "#FFFFFF",
        "level2Text": "#FFFFFF",
        "level2Background": "#7C1C2B",
        "level2ToNormalLine": "#FFFFFF",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#FFFFFF",
        "level1Text": "#000000",
        "level1Background": "#FFFFFF",
        "level1ToLevel2Line": "#FFFFFF",
        "level2Text": "#FFFFFF",
        "level2Background": "#7C1C2B",
        "level2ToNormalLine": "#FFFFFF",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#FFFFFF",
        "level1Text": "#000000",
        "level1Background": "#FFFFFF",
        "level1ToLevel2Line": "#FFFFFF",
        "level2Text": "#FFFFFF",
        "level2Background": "#7C1C2B",
        "level2ToNormalLine": "#FFFFFF",
        "normalText": "#FFFFFF",
        "normalBackground": "transparent"
      }
    ]
  },
  {
    "id": "scheme-champagne",
    "presetId": "scheme-champagne",
    "name": "香槟",
    "category": "经典",
    "appearance": "fixed",
    "background": "#EEE8E6",
    "centerText": "#000000",
    "centerBackground": "transparent",
    "cycleLength": 1,
    "branches": [
      {
        "centerToLevel1Line": "#88675E",
        "level1Text": "#000000",
        "level1Background": "#C1ABA5",
        "level1ToLevel2Line": "#88675E",
        "level2Text": "#000000",
        "level2Background": "#E6DDDA",
        "level2ToNormalLine": "#88675E",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#88675E",
        "level1Text": "#000000",
        "level1Background": "#C1ABA5",
        "level1ToLevel2Line": "#88675E",
        "level2Text": "#000000",
        "level2Background": "#E6DDDA",
        "level2ToNormalLine": "#88675E",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#88675E",
        "level1Text": "#000000",
        "level1Background": "#C1ABA5",
        "level1ToLevel2Line": "#88675E",
        "level2Text": "#000000",
        "level2Background": "#E6DDDA",
        "level2ToNormalLine": "#88675E",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#88675E",
        "level1Text": "#000000",
        "level1Background": "#C1ABA5",
        "level1ToLevel2Line": "#88675E",
        "level2Text": "#000000",
        "level2Background": "#E6DDDA",
        "level2ToNormalLine": "#88675E",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#88675E",
        "level1Text": "#000000",
        "level1Background": "#C1ABA5",
        "level1ToLevel2Line": "#88675E",
        "level2Text": "#000000",
        "level2Background": "#E6DDDA",
        "level2ToNormalLine": "#88675E",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#88675E",
        "level1Text": "#000000",
        "level1Background": "#C1ABA5",
        "level1ToLevel2Line": "#88675E",
        "level2Text": "#000000",
        "level2Background": "#E6DDDA",
        "level2ToNormalLine": "#88675E",
        "normalText": "#000000",
        "normalBackground": "transparent"
      }
    ]
  },
  {
    "id": "scheme-perfume",
    "presetId": "scheme-perfume",
    "name": "香水",
    "category": "经典",
    "appearance": "fixed",
    "background": "#EFE6C6",
    "centerText": "#000000",
    "centerBackground": "transparent",
    "cycleLength": 1,
    "branches": [
      {
        "centerToLevel1Line": "#201E14",
        "level1Text": "#000000",
        "level1Background": "#AB9446",
        "level1ToLevel2Line": "#201E14",
        "level2Text": "#000000",
        "level2Background": "#AB9446",
        "level2ToNormalLine": "#201E14",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#201E14",
        "level1Text": "#000000",
        "level1Background": "#AB9446",
        "level1ToLevel2Line": "#201E14",
        "level2Text": "#000000",
        "level2Background": "#AB9446",
        "level2ToNormalLine": "#201E14",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#201E14",
        "level1Text": "#000000",
        "level1Background": "#AB9446",
        "level1ToLevel2Line": "#201E14",
        "level2Text": "#000000",
        "level2Background": "#AB9446",
        "level2ToNormalLine": "#201E14",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#201E14",
        "level1Text": "#000000",
        "level1Background": "#AB9446",
        "level1ToLevel2Line": "#201E14",
        "level2Text": "#000000",
        "level2Background": "#AB9446",
        "level2ToNormalLine": "#201E14",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#201E14",
        "level1Text": "#000000",
        "level1Background": "#AB9446",
        "level1ToLevel2Line": "#201E14",
        "level2Text": "#000000",
        "level2Background": "#AB9446",
        "level2ToNormalLine": "#201E14",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#201E14",
        "level1Text": "#000000",
        "level1Background": "#AB9446",
        "level1ToLevel2Line": "#201E14",
        "level2Text": "#000000",
        "level2Background": "#AB9446",
        "level2ToNormalLine": "#201E14",
        "normalText": "#000000",
        "normalBackground": "transparent"
      }
    ]
  },
  {
    "id": "scheme-zen",
    "presetId": "scheme-zen",
    "name": "禅心",
    "category": "经典",
    "appearance": "fixed",
    "background": "#FFFFFF",
    "centerText": "#000000",
    "centerBackground": "transparent",
    "cycleLength": 1,
    "branches": [
      {
        "centerToLevel1Line": "#232323",
        "level1Text": "#000000",
        "level1Background": "#D6D6D6",
        "level1ToLevel2Line": "#232323",
        "level2Text": "#000000",
        "level2Background": "#D6D6D6",
        "level2ToNormalLine": "#232323",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#232323",
        "level1Text": "#000000",
        "level1Background": "#D6D6D6",
        "level1ToLevel2Line": "#232323",
        "level2Text": "#000000",
        "level2Background": "#D6D6D6",
        "level2ToNormalLine": "#232323",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#232323",
        "level1Text": "#000000",
        "level1Background": "#D6D6D6",
        "level1ToLevel2Line": "#232323",
        "level2Text": "#000000",
        "level2Background": "#D6D6D6",
        "level2ToNormalLine": "#232323",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#232323",
        "level1Text": "#000000",
        "level1Background": "#D6D6D6",
        "level1ToLevel2Line": "#232323",
        "level2Text": "#000000",
        "level2Background": "#D6D6D6",
        "level2ToNormalLine": "#232323",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#232323",
        "level1Text": "#000000",
        "level1Background": "#D6D6D6",
        "level1ToLevel2Line": "#232323",
        "level2Text": "#000000",
        "level2Background": "#D6D6D6",
        "level2ToNormalLine": "#232323",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#232323",
        "level1Text": "#000000",
        "level1Background": "#D6D6D6",
        "level1ToLevel2Line": "#232323",
        "level2Text": "#000000",
        "level2Background": "#D6D6D6",
        "level2ToNormalLine": "#232323",
        "normalText": "#000000",
        "normalBackground": "transparent"
      }
    ]
  },
  {
    "id": "scheme-rhythm",
    "presetId": "scheme-rhythm",
    "name": "律动",
    "category": "经典",
    "appearance": "fixed",
    "background": "#FFFFFF",
    "centerText": "#F44336",
    "centerBackground": "transparent",
    "cycleLength": 1,
    "branches": [
      {
        "centerToLevel1Line": "#F44336",
        "level1Text": "#FFFFFF",
        "level1Background": "#F44336",
        "level1ToLevel2Line": "#F44336",
        "level2Text": "#FFFFFF",
        "level2Background": "#F44336",
        "level2ToNormalLine": "#F44336",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#F44336",
        "level1Text": "#FFFFFF",
        "level1Background": "#F44336",
        "level1ToLevel2Line": "#F44336",
        "level2Text": "#FFFFFF",
        "level2Background": "#F44336",
        "level2ToNormalLine": "#F44336",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#F44336",
        "level1Text": "#FFFFFF",
        "level1Background": "#F44336",
        "level1ToLevel2Line": "#F44336",
        "level2Text": "#FFFFFF",
        "level2Background": "#F44336",
        "level2ToNormalLine": "#F44336",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#F44336",
        "level1Text": "#FFFFFF",
        "level1Background": "#F44336",
        "level1ToLevel2Line": "#F44336",
        "level2Text": "#FFFFFF",
        "level2Background": "#F44336",
        "level2ToNormalLine": "#F44336",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#F44336",
        "level1Text": "#FFFFFF",
        "level1Background": "#F44336",
        "level1ToLevel2Line": "#F44336",
        "level2Text": "#FFFFFF",
        "level2Background": "#F44336",
        "level2ToNormalLine": "#F44336",
        "normalText": "#000000",
        "normalBackground": "transparent"
      },
      {
        "centerToLevel1Line": "#F44336",
        "level1Text": "#FFFFFF",
        "level1Background": "#F44336",
        "level1ToLevel2Line": "#F44336",
        "level2Text": "#FFFFFF",
        "level2Background": "#F44336",
        "level2ToNormalLine": "#F44336",
        "normalText": "#000000",
        "normalBackground": "transparent"
      }
    ]
  }
] as const satisfies readonly ThemeColorAppearance[];

const APPEARANCE_BY_ID: ReadonlyMap<string, ThemeColorAppearance> = new Map(
  YEMIND_THEME_COLOR_APPEARANCES.map((item) => [item.id, item] as [string, ThemeColorAppearance]),
);
const FIXED_BY_PRESET: ReadonlyMap<string, ThemeColorAppearance> = new Map(
  YEMIND_THEME_COLOR_APPEARANCES
    .filter((item) => item.appearance === 'fixed')
    .map((item) => [item.presetId, item] as [string, ThemeColorAppearance]),
);

export function getThemeColorAppearance(presetId: unknown, appearance: 'light' | 'dark'): ThemeColorAppearance | null {
  if (typeof presetId !== 'string') return null;
  return APPEARANCE_BY_ID.get(`${presetId}-${appearance}`) ?? FIXED_BY_PRESET.get(presetId) ?? null;
}
